### PR TITLE
Siil Refrigerators Screen

### PR DESCRIPTION
**Pull request by lukaslew**
Changes to Refrigerators screen as specified in requirements.

### CODE REVIEW

**Comment by benleibert** [comment]
Hi - I apologize for the slow response to this pull-request. In the future, I'll try to reply to them much sooner.

The code looks really good, and I like com.google.common.base.Optional. It isn't clear, though, why the use of Optional is necessary and useful for RefrigeratorReadingDTO.java's newly introduced members (eg: monitoringDeviceOtherType) but not its original ones (eg: functioningCorrectly and lowAlarmEvents). Can you please update RefrigeratorReadingDTO.java such that it’s a little more consistent in this way?

I really appreciate your addition of the type-related methods (parseFloat, parseDate, etc.) to Reading.java within the “siil-visit-info-screen” branch. If it wouldn’t take much time, it would be really nice to leverage those methods within RefrigeratorReadingDTO.java to achieve better type-safety. If it would take you a while, though, it’s not something I’d ask you to do.

Thank you so much!

**Comment by lukaslew** [comment]
I updated **RefrigeratorReadingDTO** class that Optional will be used for every field from DTO class.

In other pull request I added two methods into Reading class: **parseBoolean** and **parseDate**. I am not quite sure where could I use those methods in RefrigeratorReadingDTO class. Could you tell me for what fields I could use those methods?

**Comment by benleibert** [comment]
Thank you very much! If it’s something that wouldn’t take you long, I think it would be cleaner if the new problemOccurredDate, problemReportedDate, and, equipmentRepairedDate members within RefrigeratorReadingDTO were Date rather than String values. It seems like Reading.parseDate() would help with this. Please let me know whether I’m off, though.

**Comment by lukaslew** [comment]
I changed type for those columns. Also, I found some problem with db migrations. There were several migrations with the same number but I changed migration number and now everything should work properly.

**Comment by benleibert** [comment]
Awesome - thank you very much. I really do appreciate it!

**Pull request merged**
