### PR TITLE
Feedback issues

### PR DESCRIPTION
**Pull request by skostuch**
These changes contain all fixes for the issues found while testing new SELV version.

### CODE REVIEW

**Comment by benleibert** [comment]
Hi Sebastian,

Thank you very much for your great work! I think the code looks really good and, as such, have limited my suggestions nearly exclusively to minor name changes. Please consider the following ones and let me know what you think.

Because the getDistribution methods in DistributionRepository and DistributionMapper require a Distribution as a parameter as well as return a Distribution, it isn’t clear what these methods actually do. Naming them something like getPopulatedDistribution might suggest that they’re intended to take a distribution with a limited number of set properties and populate the rest.

Similarly, the getDistribution method in DistributionService that returns a DistributionDTO might ideally be named getDistributionDTO.

It’s great that the “distribution.period.allowed.months” configuration option is commented. It’s name, though, suggests that it means to configure which months configurations are allowed to start within. Perhaps a more descriptive name would be something like “distributions.display.month.limit.” 

Renaming DistributionPeriodPredicate to something a bit more descriptive (perhaps “DistributionStartsWithinMonthLimit”) could make the code a little more self-explanatory.

Based on the updateRefrigeratorInStore function in refrigerator-controller.js, it looks as though the UI silently ignores the user’s input if they try to reuse a pre-existing refrigerator’s serial number. Is that indeed the case? I would hope that the user would be given an indication that their request failed and an explanation why.

Kind regards,
Ben

**Comment by skostuch** [comment]
Hi Ben,
thank you very much for your comments. I've made the suggested changes to the code. When it comes to the updateRefrigeratorInStore function: do you mean the following code?

`if (existing && $scope.refrigeratorReading.refrigerator.serialNumber.value !== $scope.oldSerialNumberValue) {
      $scope.isDuplicateSerialNumber = true;
}`

If yes, then this check was added to ensure that user will not change Serial Number for the existing refrigerator to the same ones as the other refrigerator has (we still require this to be unique). This check however allows us to distinguish if the found refrigerator with the same Serial Number is in fact the same which user actually edits (then we allow this) or if this is another one then we print "Duplicate Identifier / Serial number" and user is not able to confirm his changes unless he uses different Serial Number.

Regards
Sebastian

**Comment by benleibert** [comment]
Hi Sebastian,

Thank you very much for making those tweaks – everything looks really you. You indeed identified the piece of code I was referring to in the updateRefrigeratorInStore function. I had overlooked the duplicateSerialNumberError div in refrigerator.html (which works exactly as you described) and apologize for that oversight. 

The pull-request’s content has been merged into selv-dev, and its branch can probably be deleted any time you see fit. Again – thank you very much!

Kind regards,
Ben

**Comment by skostuch** [comment]
Hi Ben,
thank you very much for the review. We've also received the feedback 
about missing translations and the issue with Child Coverage status icon 
not changing properly to green when all fields were completed so we've 
fixed that and these changes are also ready for review. There is PR 
(using the same feedback-issues branch) for that, the changes are really 
minor, but we would appreciate if you could look at them and review as 
well. Thank you.

Regards
Sebastian

**Pull request merged**
